[package]
name = "mp4datecorrector"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
file-format = "0.25.0"
walkdir = "2.5.0"
nom-exif = "1.3.0"
chrono =  { version = "0.4.38", features = ["std"] }
