[package]
name = "media_file_date_fixer"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
nom-exif = "2.5.1"
chrono =  { version = "0.4.40", features = ["std"] }
pathdiff = "0.2.3"
cfg-if = "1.0.0"

[[bin]]
name = "mfdf"
path = "src/main.rs"
